model:
  base_learning_rate: 5.0e-3
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 32
    channels: 4
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    embedding_reg_weight: 0.0

    personalization_config:
      target: ldm.modules.embedding_manager.EmbeddingManager
      params:
        placeholder_strings: ["*"]
        initializer_words: ["sculpture"]
        per_image_tokens: false
        num_vectors_per_token: 1
        progressive_words: False

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 1280
        use_checkpoint: true
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.BERTEmbedder
      params:
        n_embed: 1280
        n_layer: 32


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4 #increase once you request a different gpu
    num_workers: 1 #default is 2 #reduce num workers to 1(?) when youre training/optimizing embedding, num workers just loads data in parallel
    #if you have 8 images, it'll keep another batch loaded. If i use just 1 worker only one batch will be loaded at once
    wrap: false
    train:
      target: ldm.data.personalized.PersonalizedBase
      params:
        size: 256
        set: train
        per_image_tokens: false
        repeats: 80 #100 #can change - what 100 means that each image in dataset can be copied 100 times (so training set increases)
        #reduce repeats from 100 to 10, or even 1, 
    validation:
      target: ldm.data.personalized.PersonalizedBase
      params:
        size: 256
        set: val
        per_image_tokens: false
        repeats: 10 #can change as well #default 10

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 500
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    max_steps: 12200 #18300 #6100 #increase max steps by 10 times, maybe increase by a lot more, 